version: "3.7"

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app_container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - ftp
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin_container
    restart: unless-stopped
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db_container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  ftp:
    image: stilliard/pure-ftpd
    container_name: laravel_ftp_container
    restart: always
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "ftpuser"
      FTP_USER_PASS: "ftppassword"
      FTP_USER_HOME: "/home/ftpuser"
    volumes:
      - ftp_data:/home/ftpuser
    networks:
      - laravel_network

volumes:
  db_data:
  ftp_data:

networks:
  laravel_network:
    driver: bridge
